### ISSUE TITLE
Initial sensor values are zero on start up

### ISSUE THREAD

**Issue by EK701** [rsnodgrass/hass-sensorpush#2]
I'm running HA in a docker container under Ubuntu. Everything is working fine, except every time HA is restarted, the initial sensor reading from all sensors is 0.

**Comment by rsnodgrass** [comment]
Thanks for posting this.  I'll  look into this and restart mine to see if I can reproduce.  I wonder if some sort of timeout contacting SensorPush's web API is happening on startup.

**Comment by EK701** [comment]
I turned debugging on and it didn't appear to be a timeout contacting the API.  I can run it again if it's helpful.

**Comment by EK701** [comment]
I see you made a new commit to fix this.  However, things are now completely broken:

2019-11-12 22:30:47 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.sensorpush
2019-11-12 22:30:50 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform sensorpush
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/sensorpush/sensor.py", line 55, in async_setup_platform
    hass_sensors.append(SensorPushTemperature(hass, conf, sensor_info, unit_system))
  File "/config/custom_components/sensorpush/sensor.py", line 84, in __init__
    super().__init__(hass, config, sensor_info, unit_system, 'temperature')
  File "/config/custom_components/sensorpush/__init__.py", line 133, in __init__
    self._update_callback()
  File "/config/custom_components/sensorpush/__init__.py", line 178, in _update_callback
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 421, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'

**Comment by EK701** [comment]
I've played around with this a bit and found a simple solution.  In sensors.py, change:

self._state = 0.0

to

self._state = ""

It results in a null initial value displayed, but it doesn't enter a value of 0.0 into the database.

**Comment by rsnodgrass** [comment]
Thanks.  Simple solution!  Sorry I didn't have time to dig into this yet.
